[2014-10-31 10:27:17.405] [INFO] normal - SMTP Configured
[2014-10-31 10:27:20.504] [INFO] normal - mongodb已连接
[2014-10-31 10:28:16.830] [INFO] normal - SMTP Configured
[2014-10-31 10:28:16.875] [INFO] normal - mongodb已连接
[2014-10-31 10:28:31.510] [INFO] normal - -----------------------------成功-----------------------
[2014-10-31 10:28:31.542] [INFO] normal - -----------------------------成功-----------------------
[2014-10-31 12:00:37.529] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:39.536] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:41.542] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:43.546] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:45.550] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:47.558] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:49.593] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:51.600] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:53.611] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:55.618] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:57.628] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:00:59.619] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:01.626] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:03.623] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:05.630] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:07.620] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:09.628] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:11.635] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:13.642] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:15.648] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:17.655] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:19.662] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:21.667] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:23.677] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:25.694] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:27.714] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:29.728] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:31.741] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:33.745] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:35.751] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:37.761] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:39.775] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:41.796] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:43.803] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:45.816] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:47.808] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:49.815] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:51.811] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:53.810] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:55.807] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:57.809] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:01:59.821] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:01.836] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:03.844] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:05.846] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:07.844] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:09.839] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:11.848] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:13.856] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:15.868] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:17.875] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:19.871] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:21.876] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:23.873] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:25.869] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:27.883] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:29.896] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:31.897] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:33.909] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:35.905] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:37.919] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:39.930] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:41.946] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:43.960] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:45.964] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:47.977] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:49.992] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:52.004] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:54.001] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:55.999] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:57.998] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:02:59.996] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:02.009] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:04.023] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:06.040] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:08.053] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:10.068] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:12.067] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:14.054] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:16.069] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:18.074] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:20.092] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:22.092] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:24.090] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:26.097] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:28.099] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:30.098] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:32.099] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:34.099] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:36.101] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:38.103] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:40.127] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:42.123] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:44.119] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:46.131] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:48.142] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:50.139] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:52.134] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:54.147] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:56.133] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:03:58.147] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:04:00.157] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
[2014-10-31 12:04:01.847] [ERROR] normal - 连接mongodb数据库失败:Error: failed to connect to [192.168.1.33:27017]
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:546:74)
    at emit (events.js:106:17)
    at null.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (E:\workpace\server\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:533:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
